# ============================================================================ #
#                   Django settings for Shaurmania project.                    #
#         Generated by 'django-admin startproject' using Django 5.1.3.         #
# ============================================================================ #
from logging import CRITICAL

import environ

from pathlib import Path
from os import path

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env( path.join( BASE_DIR, '.env' ) )


# SECURITY SETTINGS ============================================================

SECRET_KEY    = env( "SECRET_KEY" )
DEBUG         = env( "DEBUG" )
IS_DDT_ACTIVE = env( "IS_DDT_ACTIVE", default = False )

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

INTERNAL_IPS = [
    "127.0.0.1",
]


# APPLICATION DEFINITION =======================================================

ROOT_URLCONF = "Shaurmania.urls"
WSGI_APPLICATION = "Shaurmania.wsgi.application"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "compressor",
    "imagekit",
    "django_jinja",

    "main.apps.MainConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# DJANGO DEBUG TOOL ============================================================

if IS_DDT_ACTIVE:
    INSTALLED_APPS += [ "debug_toolbar", ]

    DEBUG_TOOLBAR_CONFIG = {
        'DISABLE_PANELS': [
            'debug_toolbar.panels.cache.CachePanel',
        ],
    }

    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")


# TEMPLATES SETTINGS ===========================================================

TEMPLATES = [
    {
        "BACKEND": "django_jinja.jinja2.Jinja2",
        "DIRS": [ BASE_DIR / "template" ],
        "APP_DIRS": True,
        "OPTIONS": {
            'match_extension': '.jinja',
            'match_regex'    : None,
            'app_dirname'    : 'templates',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'extensions': [
                'jinja2.ext.i18n',
                'django_jinja.builtins.extensions.DebugExtension',
                'django_jinja.builtins.extensions.StaticFilesExtension',
                'django_jinja.builtins.extensions.CacheExtension',
                'django_jinja.builtins.extensions.CsrfExtension',
                'django_jinja.builtins.extensions.UrlsExtension',
                "django_jinja.builtins.extensions.TimezoneExtension",
                'django_jinja.builtins.extensions.DjangoFiltersExtension',
                'compressor.contrib.jinja2ext.CompressorExtension'
            ],
            "policies": {
                "ext.i18n.trimmed": True,
            },
            "bytecode_cache": {
                "name": "default",
                "backend": "django_jinja.cache.BytecodeCache",
                "enabled": True,
            },
            "autoescape": True,
        }
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / "template" ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# DATABASE SETTINGS ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / env( 'DATABASE_NAME' ),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'main.User'


# LOGS SUBSYSTEM ===============================================================

LOG_DIR = BASE_DIR / env( 'LOG_DIR', default = 'logs' )
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[ {asctime} ] {levelname: <8} | {name} : {message}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} | {levelname} | {message}',
            'datefmt': '%H:%M:%S',
            'style': '{'
        }
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * env('LOG_FILE_SIZE', default = 2),
            'backupCount': env('LOG_BACKUP_COUNT', default = 10),
            'formatter': 'verbose',
        },
        'file_server': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'server.log',
            'maxBytes': 1024 * 1024 * env('LOG_FILE_SIZE', default = 2),
            'backupCount': env('LOG_BACKUP_COUNT', default = 10),
            'formatter': 'verbose',
        },
        'file_database': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'database.log',
            'maxBytes': 1024 * 1024 * env('LOG_FILE_SIZE', default = 2),
            'backupCount': env('LOG_BACKUP_COUNT', default = 10),
            'formatter': 'verbose',
        },
        'file_errors': {
            'class'      : 'logging.handlers.RotatingFileHandler',
            'filename'   : LOG_DIR / 'errors.log',
            'maxBytes'   : 1024 * 1024 * env( 'LOG_FILE_SIZE', default = 2 ),
            'backupCount': env( 'LOG_BACKUP_COUNT', default = 10 ),
            'formatter'  : 'verbose',
            'level'      : 'ERROR',
        },
    },

    'root': {
        'handlers': [ 'console', 'file', 'file_errors' ],
        'level': env('ROOT_LOG_LEVEL', default = 'INFO'),
    },

    'loggers': {
        'django': {
            'handlers': [ 'console', 'file', 'file_server' ],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': [ 'file', 'file_server' ],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': [ 'file', 'file_database' ],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.security': {
            'handlers': [ 'file', 'file_server' ],
            'level': 'WARNING',
            'propagate': False,
        },
        'main': {
            'handlers': [ 'console', 'file', 'file_server' ],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# PASSWORD VALIDATION ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# INTERNATIONALIZATION =========================================================

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# STATIC FILES =================================================================

STATIC_URL = env('STATIC_URL', default='static/')
STATIC_ROOT = BASE_DIR / 'static_root'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL  = env('MEDIA_URL', default='media/')
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder'
)

COMPRESS_ENABLED = env('IS_COMPRESS_ENABLED', default = True)


# OTHER SETTINGS ===============================================================

AVATARS_COUNT = 81
