# ============================================================================ #
#                   Django settings for Shaurmania project.                    #
#         Generated by 'django-admin startproject' using Django 5.1.3.         #
# ============================================================================ #

import environ

from pathlib import Path
from os import path

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env( path.join( BASE_DIR, '.env' ) )


# SECURITY SETTINGS ============================================================

SECRET_KEY = env( "SECRET_KEY" )
DEBUG = env( "DEBUG" )

ALLOWED_HOSTS = []


# APPLICATION DEFINITION =======================================================

ROOT_URLCONF = "Shaurmania.urls"
WSGI_APPLICATION = "Shaurmania.wsgi.application"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django_jinja",

    "main.apps.MainConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django_jinja.jinja2.Jinja2",
        "DIRS": [ BASE_DIR / "template" ],
        "APP_DIRS": True,
        "OPTIONS": {
            'match_extension': '.jinja',
            'match_regex'    : None,
            'app_dirname'    : 'templates',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'extensions': [
                'jinja2.ext.i18n',
                'django_jinja.builtins.extensions.DebugExtension',
                'django_jinja.builtins.extensions.StaticFilesExtension',
                'django_jinja.builtins.extensions.CacheExtension',
                'django_jinja.builtins.extensions.CsrfExtension',
                'django_jinja.builtins.extensions.UrlsExtension',
                "django_jinja.builtins.extensions.TimezoneExtension",
                'django_jinja.builtins.extensions.DjangoFiltersExtension',
            ],
            "policies": {
                "ext.i18n.trimmed": True,
            },
            "bytecode_cache": {
                "name": "default",
                "backend": "django_jinja.cache.BytecodeCache",
                "enabled": True,
            },
            "autoescape": True,
        }
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / "template" ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# DATABASE SETTINGS ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / env( 'DATABASE_NAME' ),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'main.User'


# PASSWORD VALIDATION ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# INTERNATIONALIZATION =========================================================

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# STATIC FILES =================================================================

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL  = 'media/'
MEDIA_ROOT = 'media'


# OTHER SETTINGS ===============================================================

AVATARS_COUNT = 81
