# Generated by Django 6.0 on 2025-12-13 03:36

import django.core.validators
import django.db.models.deletion
import main.models.user
import main.validators
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='achievement_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=70, verbose_name='URL-адрес')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('planet', models.CharField(default='Земля', max_length=60, verbose_name='Планета')),
                ('country', models.CharField(default='Россия', max_length=60, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('address', models.CharField(max_length=60, verbose_name='Адрес')),
                ('picture', models.ImageField(upload_to='locations', verbose_name='Изображение')),
                ('timeline', models.CharField(choices=[('PST', 'Прошлое'), ('NOW', 'Настоящее'), ('FTR', 'Будущее')], default='NOW', max_length=3, verbose_name='Время')),
                ('contacts', models.CharField(max_length=60, verbose_name='Контакты')),
                ('open_hours', models.TimeField(verbose_name='Начало')),
                ('close_hours', models.TimeField(verbose_name='Конец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'заведениe',
                'verbose_name_plural': 'заведения',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=60, verbose_name='URL-адрес тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'новостной тег',
                'verbose_name_plural': 'новостные теги',
            },
        ),
        migrations.CreateModel(
            name='Shaurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=70, verbose_name='URL-адрес')),
                ('compound', models.TextField(max_length=600, verbose_name='Состав')),
                ('short_text', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('history', models.TextField(blank=True, max_length=1000, verbose_name='История')),
                ('picture', models.ImageField(upload_to='shaurma_images', verbose_name='Изображение')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена в ₽')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес в гр')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории (ккал)')),
                ('proteins', models.FloatField(default=0, verbose_name='Белки (г)')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры (г)')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='Углеводы (г)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'шаурма',
                'verbose_name_plural': 'шаурма',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShaurmaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'категория шаурмы',
                'verbose_name_plural': 'категории шаурмы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=40, validators=[main.validators.validate_not_in_stop_words], verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Отчество')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Описание')),
                ('last_address', models.CharField(blank=True, max_length=200, verbose_name='Адрес последней доставки')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Null')], default='N', max_length=1, verbose_name='Пол')),
                ('main_lang', models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], default='RU', max_length=2, verbose_name='Язык')),
                ('username', models.CharField(db_index=True, max_length=60, unique=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Никнейм')),
                ('email', models.EmailField(db_index=True, max_length=80, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('email_status', models.CharField(choices=[('N', 'None'), ('V', 'Verified'), ('R', 'Reality Verified')], default='N', max_length=1, verbose_name='Статус email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон')),
                ('phone_status', models.CharField(choices=[('N', 'None'), ('V', 'Verified'), ('R', 'Reality Verified')], default='N', max_length=1, verbose_name='Статус телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[main.models.user.validate_age], verbose_name='Дата рождения')),
                ('register_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='Открытый профиль?')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Профиль активен?')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Это сотрудник сайта?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=110, verbose_name='URL-адрес')),
                ('short_text', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('rich_content', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Изображение 16 на 9')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Доступна для показа')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная новость')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, to='main.newstag', verbose_name='Новостные теги')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('text', models.TextField(max_length=600, verbose_name='Текст отзыва')),
                ('stars', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('shaurma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shaurma', verbose_name='Шаурма')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shaurma',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shaurmacategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ShaurmaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shaurma_additional', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, default='Фото нашей шаурмы', max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shaurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shaurma', verbose_name='Шаурма')),
            ],
            options={
                'verbose_name': 'изображение шаурмы',
                'verbose_name_plural': 'изображения шаурмы',
                'ordering': ['shaurma', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=70, verbose_name='URL-адрес')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('short_text', models.CharField(blank=True, max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('condition', models.TextField(blank=True, max_length=1000, verbose_name='Условия акции')),
                ('image', models.ImageField(upload_to='stocks', verbose_name='Изображение')),
                ('discount', models.SmallIntegerField(verbose_name='Скидка в %')),
                ('date_start', models.DateField(verbose_name='Старт')),
                ('date_end', models.DateField(verbose_name='Завершение')),
                ('categories', models.ManyToManyField(blank=True, to='main.shaurmacategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'достижение пользователя',
                'verbose_name_plural': 'достижения пользователей',
                'ordering': ['get_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Аватар')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной аватар')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'аватар',
                'verbose_name_plural': 'аватары',
                'ordering': ['user', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'is_primary'), name='one_primary_avatar')],
            },
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('FB', 'Facebook'), ('GH', 'GitHub'), ('IG', 'Instagram'), ('LN', 'LinkedIn'), ('OK', 'Одноклассники'), ('PT', 'Pinterest'), ('RD', 'Reddit'), ('SC', 'Snapchat'), ('TG', 'Telegram'), ('TT', 'TikTok'), ('TW', 'Twitter'), ('VK', 'ВКонтакте'), ('WA', 'WhatsApp'), ('YT', 'YouTube')], max_length=2, verbose_name='Соцсеть')),
                ('link', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Ссылка проверена')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главная ссылка')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Ссылка отображается')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
                'ordering': ['user', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'network', 'is_primary'), name='one_primary_link')],
            },
        ),
    ]
