# Generated by Django 5.2.1 on 2025-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=17, verbose_name='Номер'),
        ),
    ]
