# Generated by Django 6.0 on 2025-12-13 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Дом, Работа и т.д.', null=True, verbose_name='Подпись')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки доставки')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='geodata.address', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Адрес пользователя',
                'verbose_name_plural': 'Адреса пользователей',
                'ordering': ['-is_default', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='one_default_address_per_user'), models.UniqueConstraint(fields=('user', 'address'), name='unique_address_per_user')],
            },
        ),
    ]
