# Generated by Django 5.2.1 on 2025-05-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='review',
            name='shaurma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shaurma', verbose_name='Шаурма'),
        ),
    ]
