# Generated by Django 5.1.3 on 2025-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('compound', models.TextField(max_length=600)),
                ('description', models.TextField(max_length=600)),
                ('picture', models.ImageField(upload_to='shaurma_images')),
                ('price', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
