# Generated by Django 5.1.3 on 2025-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name'], 'verbose_name': 'достижение', 'verbose_name_plural': 'достижения'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['get_date'], 'verbose_name': 'достижение пользователя', 'verbose_name_plural': 'достижения пользователей'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='сontacts',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='сondition',
            new_name='condition',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Никнейм'),
        ),
    ]
