# Generated by Django 5.1.3 on 2025-02-02 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shaurma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, verbose_name='Адрес')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'заведениe',
                'verbose_name_plural': 'заведения',
                'ordering': ['address'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['name'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='shaurma',
            options={'ordering': ['name'], 'verbose_name': 'шаурма', 'verbose_name_plural': 'шаурма'},
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Дата/Время записи'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=600, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='compound',
            field=models.TextField(max_length=600, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='picture',
            field=models.ImageField(upload_to='shaurma_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена в ₽'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Вес в гр'),
        ),
    ]
