# Generated by Django 5.2.1 on 2025-06-08 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quanity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('shaurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shaurma', verbose_name='Шаурма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-order_id'],
            },
        ),
    ]
