# Generated by Django 6.0 on 2025-12-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('main', '0002_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='Стоимость доставки')),
                ('delivery_speed', models.CharField(choices=[('XS', 'Очень медленно'), ('S', 'Meдленно'), ('M', 'Средне'), ('F', 'Быстро'), ('EF', 'Очень быстро')], default='M', max_length=2, verbose_name='Скорость доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.geocity', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'доставка в города',
                'verbose_name_plural': 'доставка в города',
                'ordering': ['city'],
            },
        ),
    ]
