# Generated by Django 6.0.1 on 2026-01-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaurma',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='shaurma',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaurmas', to='main.shaurmacategory', verbose_name='Категория'),
        ),
    ]
