# Generated by Django 5.2.1 on 2025-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='shaurma',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('carted', 'В корзине'), ('cancelled', 'Отменен'), ('ordered', 'Куплен'), ('completed', 'Завершен')], default='carted', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
