# Generated by Django 5.2.1 on 2025-10-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quanity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quanity'),
        ),
    ]
