# Generated by Django 5.1.3 on 2025-02-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review_shaurma'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='Юзернейм')),
                ('picture', models.ImageField(upload_to='user_images', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='shaurma',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='main.shaurma', verbose_name='Шаурма'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shaurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shaurma', verbose_name='Шаурма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
        ),
    ]
