# Generated by Django 5.2.1 on 2025-10-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shaurma',
            new_name='item',
        ),
    ]
