# Generated by Django 5.2.1 on 2025-10-20 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_shaurma_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaurma',
            name='history',
            field=models.TextField(blank=True, max_length=1000, verbose_name='История'),
        ),
        migrations.CreateModel(
            name='ShaurmaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shaurma_additional', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, default='Фото нашей шаурмы', max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shaurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shaurma', verbose_name='Шаурма')),
            ],
            options={
                'verbose_name': 'изображение шаурмы',
                'verbose_name_plural': 'изображения шаурмы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
