# Generated by Django 5.1.3 on 2025-04-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_alter_review_shaurma_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='achievement_image', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес последней доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default=1, max_length=12, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-04 10:10'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
        ),
    ]
