# Generated by Django 5.1.3 on 2025-05-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_achievement_user_email_user_last_address_user_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('discount', models.SmallIntegerField(verbose_name='Скидка')),
                ('product', models.CharField(max_length=40, verbose_name='Товар')),
                ('сondition', models.CharField(max_length=40, verbose_name='Условие')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
                'ordering': ['name'],
            },
        ),
    ]
