# Generated by Django 5.2.1 on 2025-10-27 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shaurma_history_shaurmaimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shaurmaimage',
            options={'ordering': ['shaurma', 'order'], 'verbose_name': 'изображение шаурмы', 'verbose_name_plural': 'изображения шаурмы'},
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='planet',
            field=models.CharField(default='Земля', max_length=60, verbose_name='Планета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='timeline',
            field=models.CharField(choices=[('PST', 'Прошлое'), ('NOW', 'Настоящее'), ('FTR', 'Будущее')], default='NOW', max_length=3, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contacts',
            field=models.CharField(max_length=60, verbose_name='Контакты'),
        ),
    ]
