# Generated by Django 5.2.1 on 2025-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shaurmaimage_options_location_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='URL-адрес'),
        ),
    ]
