# Generated by Django 5.1.3 on 2025-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(default='', max_length=20, verbose_name='Время работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='', upload_to='locations', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='сontacts',
            field=models.CharField(default='', max_length=12, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='discount',
            field=models.SmallIntegerField(verbose_name='Скидка в %'),
        ),
    ]
