# Generated by Django 5.2.1 on 2025-10-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Россия', max_length=60, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='location',
            name='planet',
            field=models.CharField(default='Земля', max_length=60, verbose_name='Планета'),
        ),
    ]
