# Generated by Django 6.0b1 on 2025-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_cart_item_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=110, verbose_name='URL-адрес')),
                ('short_text', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='news_images', verbose_name='Изображение')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Доступна для показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['created_at', 'title'],
            },
        ),
    ]
