# Generated by Django 6.0b1 on 2025-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL-адрес тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важная новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Изображение 16 на 9'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.newstag', verbose_name='Новостные теги'),
        ),
    ]
