# Generated by Django 6.0b1 on 2025-11-22 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newstag_alter_news_options_remove_news_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name': 'новостной тег', 'verbose_name_plural': 'новостные теги'},
        ),
        migrations.AddField(
            model_name='newstag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newstag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='URL-адрес тега'),
        ),
    ]
