# Generated by Django 6.0b1 on 2025-11-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_newstag_options_newstag_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstag',
            name='updated_at',
        ),
    ]
