# Generated by Django 6.0b1 on 2025-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_newstag_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main_text',
        ),
        migrations.AddField(
            model_name='news',
            name='rich_content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='main.newstag', verbose_name='Новостные теги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
    ]
