# Generated by Django 6.0b1 on 2025-11-23 02:12

import django.utils.timezone
import main.models.user
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_news_main_text_news_rich_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[main.models.user.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=240, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=models.CharField(choices=[('N', 'None'), ('V', 'Verified'), ('R', 'Reality Verified')], default='N', max_length=1, verbose_name='Статус email'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_lang',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], default='RU', max_length=2, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='SS', max_length=40, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='88005553535', max_length=128, region=None, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_status',
            field=models.CharField(choices=[('N', 'None'), ('V', 'Verified'), ('R', 'Reality Verified')], default='N', max_length=1, verbose_name='Статус телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Null')], default='N', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=80, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес последней доставки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Никнейм'),
        ),
    ]
