# Generated by Django 6.0b1 on 2025-11-28 06:09

import django.core.validators
import django.db.models.deletion
import main.validators
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Профиль активен?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Открытый профиль?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Это сотрудник сайта?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, validators=[main.validators.validate_not_in_stop_words], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=60, unique=True, validators=[main.validators.validate_not_in_stop_words], verbose_name='Никнейм'),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Аватар')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной аватар')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'аватар',
                'verbose_name_plural': 'аватары',
                'ordering': ['user', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'is_primary'), name='one_primary_avatar')],
            },
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('FB', 'Facebook'), ('GH', 'GitHub'), ('IG', 'Instagram'), ('OK', 'Одноклассники'), ('TG', 'Telegram'), ('VK', 'ВКонтакте'), ('YT', 'YouTube')], max_length=2, verbose_name='Соцсеть')),
                ('link', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
                'ordering': ['user', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'network', 'is_primary'), name='one_primary_link')],
            },
        ),
    ]
