# Generated by Django 6.0b1 on 2025-11-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_user_avatar_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersociallink',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Ссылка отображается'),
        ),
        migrations.AlterField(
            model_name='usersociallink',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главная ссылка'),
        ),
        migrations.AlterField(
            model_name='usersociallink',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Ссылка проверена'),
        ),
        migrations.AlterField(
            model_name='usersociallink',
            name='network',
            field=models.CharField(choices=[('FB', 'Facebook'), ('GH', 'GitHub'), ('IG', 'Instagram'), ('LN', 'LinkedIn'), ('OK', 'Одноклассники'), ('PT', 'Pinterest'), ('RD', 'Reddit'), ('SC', 'Snapchat'), ('TG', 'Telegram'), ('TT', 'TikTok'), ('TW', 'Twitter'), ('VK', 'ВКонтакте'), ('WA', 'WhatsApp'), ('YT', 'YouTube')], max_length=2, verbose_name='Соцсеть'),
        ),
    ]
