# Generated by Django 6.0 on 2025-12-13 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=20, unique=True, verbose_name='Код действия')),
                ('action_name', models.CharField(max_length=30, verbose_name='Название действия')),
                ('template', models.CharField(max_length=250, verbose_name='Шаблон уведомления')),
                ('action_value', models.SmallIntegerField(choices=[(1, 'Мусорное'), (2, 'Неважное'), (3, 'Обычное'), (4, 'Важное'), (5, 'Критическое')], default=3, verbose_name='Сила важности уведомления')),
            ],
            options={
                'verbose_name': 'тип уведомления безопасности',
                'verbose_name_plural': 'типы уведомлений безопасности',
                'db_table': 'security_action',
            },
        ),
        migrations.CreateModel(
            name='SecurityDevice',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID устройства')),
                ('user_agent_full', models.CharField(max_length=255, null=True, verbose_name='Полный User-Agent')),
                ('browser_name', models.CharField(max_length=40, null=True, verbose_name='Браузер / имя')),
                ('browser_version', models.CharField(max_length=40, null=True, verbose_name='Браузер / версия полная')),
                ('browser_major', models.CharField(max_length=10, null=True, verbose_name='Браузер / версия')),
                ('device_vendor', models.CharField(max_length=40, null=True, verbose_name='Устройство / производитель')),
                ('device_model', models.CharField(max_length=40, null=True, verbose_name='Устройство / модель')),
                ('device_type', models.CharField(max_length=20, null=True, verbose_name='Устройство / тип')),
                ('engine_name', models.CharField(max_length=20, null=True, verbose_name='Движок / имя')),
                ('engine_version', models.CharField(max_length=20, null=True, verbose_name='Движок / версия')),
                ('os_name', models.CharField(max_length=40, null=True, verbose_name='ОС / Имя')),
                ('os_version', models.CharField(max_length=20, null=True, verbose_name='ОС / Версия')),
                ('cpu', models.CharField(max_length=20, null=True, verbose_name='Процессор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
                'db_table': 'security_device',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP входа')),
                ('is_success', models.BooleanField(db_index=True, default=True, verbose_name='Успешность входа')),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время входа')),
                ('logout_at', models.DateTimeField(blank=True, default=None, verbose_name='Время выхода')),
                ('ip_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.geocountry', verbose_name='Страна по IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auths', to='security.securitydevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'лог авторизации',
                'verbose_name_plural': 'логи авторизации',
                'db_table': 'security_auth_log',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('channel', models.CharField(default='website', max_length=20, verbose_name='Канал отправки')),
                ('notice_at', models.DateTimeField(auto_now_add=True, verbose_name='Время уведомления')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.securityaction', verbose_name='Действие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_notices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уведомление безопасности',
                'verbose_name_plural': 'уведомления безопасности',
                'db_table': 'security_notice',
                'ordering': ['-notice_at'],
            },
        ),
    ]
