# Generated by Django 6.0 on 2025-12-13 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Геокодер счётчик',
                'verbose_name_plural': 'Геокодер счётчики',
                'db_table': 'tech_geocode_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GeoCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название RUS')),
                ('name_official_ru', models.CharField(max_length=150, verbose_name='Название (офф) RUS')),
                ('name_en', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название ENG')),
                ('name_official_en', models.CharField(max_length=150, verbose_name='Название (офф) ENG')),
                ('capital_ru', models.CharField(max_length=40, verbose_name='Столица RUS')),
                ('capital_en', models.CharField(max_length=40, verbose_name='Столица ENG')),
                ('emoji_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Код')),
                ('emoji_flag', models.CharField(blank=True, max_length=5, null=True, verbose_name='Флажок')),
                ('flag', models.FileField(blank=True, null=True, upload_to='geo/flags', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Флаг SVG')),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Код валюты')),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название валюты')),
                ('currency_symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Символ валюты')),
                ('phone_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код телефона')),
                ('cca2', models.CharField(blank=True, max_length=2, null=True, verbose_name='2букв код страны')),
                ('cca3', models.CharField(blank=True, max_length=3, null=True, verbose_name='3букв код страны')),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True, verbose_name='3знач код страны')),
                ('top_level_domain', models.CharField(blank=True, max_length=5, null=True, verbose_name='Код домена')),
                ('is_landlocked', models.BooleanField(default=False, verbose_name='Только суша?')),
                ('is_independent', models.BooleanField(default=True, verbose_name='Страна независима?')),
                ('is_member_oon', models.BooleanField(default=True, verbose_name='Входит в ООН?')),
                ('area', models.PositiveBigIntegerField(verbose_name='Площадь')),
                ('population', models.PositiveBigIntegerField(verbose_name='Население')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта центра')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота центра')),
                ('wiki_data_id', models.CharField(max_length=20, unique=True, verbose_name='Wikipedia ID')),
                ('is_handly_verify', models.BooleanField(default=False, verbose_name='Проверено вручную')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': '2. Страны мира',
                'db_table': 'geo_countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeoNodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Тип узла ENG')),
                ('name_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Тип узла RUS')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание типа узла ENG')),
                ('description_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание типа узла RUS')),
            ],
            options={
                'verbose_name': 'тип гео-узла',
                'verbose_name_plural': 'типы гео-узлов',
                'db_table': 'geo_nodes_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeoPartWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название RUS')),
                ('name_en', models.CharField(max_length=20, unique=True, verbose_name='Название ENG')),
                ('wiki_data_id', models.CharField(max_length=20, unique=True, verbose_name='Wikipedia ID')),
            ],
            options={
                'verbose_name': 'часть света',
                'verbose_name_plural': '0. Части света',
                'db_table': 'geo_parts_world',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeoStreetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_ru', models.CharField(db_index=True, max_length=10, verbose_name='Тип ( краткий | RUS )')),
                ('short_en', models.CharField(db_index=True, max_length=10, verbose_name='Тип ( краткий | ENG )')),
                ('long_ru', models.CharField(max_length=30, verbose_name='Тип ( полный | RUS )')),
                ('long_en', models.CharField(max_length=30, verbose_name='Тип ( полный | ENG )')),
                ('variants_ru', models.JSONField(db_index=True, default=list, help_text='["ул.", "ул", "улица", "улице", "улицы"]', verbose_name='Варианты ( RUS )')),
                ('variants_en', models.JSONField(db_index=True, default=list, help_text='["St.", "St", "street", "str.", "ul."]', verbose_name='Варианты ( RUS )')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок сортировки в выпадающем списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'тип улицы',
                'verbose_name_plural': 'типы улиц',
                'db_table': 'geo_streets_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.CharField(max_length=64, unique=True, verbose_name='Таймзона (IANA)')),
                ('shift', models.IntegerField(verbose_name='Смещение UTC (часы)')),
            ],
            options={
                'verbose_name': 'таймзона',
                'verbose_name_plural': 'таймзоны',
                'db_table': 'geo_timezones',
                'ordering': ['tz'],
            },
        ),
        migrations.CreateModel(
            name='GeoNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('name_ru', models.CharField(db_index=True, max_length=250, verbose_name='Название RUS')),
                ('name_en', models.CharField(max_length=250, verbose_name='Название ENG')),
                ('name_native', models.CharField(max_length=250, verbose_name='Родное название')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта центра')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота центра')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('iso_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ICO 3166-2')),
                ('wiki_data_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wikipedia ID')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(db_index=True, verbose_name='Обновлено')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='geodata.geocountry', verbose_name='Страна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geodata.geonode', verbose_name='Родитель')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='geodata.geonodetype', verbose_name='Тип узла')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.timezone', verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'гео-узел',
                'verbose_name_plural': '3. Гео-узлы',
                'db_table': 'geo_nodes',
                'ordering': ['country', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(db_index=True, max_length=250, verbose_name='Название RUS')),
                ('name_en', models.CharField(max_length=250, verbose_name='Название ENG')),
                ('name_native', models.CharField(max_length=250, verbose_name='Родное название')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('wiki_data_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wikipedia ID')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(verbose_name='Дата/время изменения')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geodata.geonode', verbose_name='Регион')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.timezone', verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': '4. Города',
                'db_table': 'geo_cities',
                'ordering': ['node', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='GeoRegionWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название RUS')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='Название ENG')),
                ('wiki_data_id', models.CharField(max_length=20, unique=True, verbose_name='Wikipedia ID')),
                ('part_world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions_world', to='geodata.geopartworld', verbose_name='Часть света')),
            ],
            options={
                'verbose_name': 'регион мира',
                'verbose_name_plural': '1. Регионы мира',
                'db_table': 'geo_regions_world',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='geocountry',
            name='region_world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='geodata.georegionworld', verbose_name='Регион мира'),
        ),
        migrations.CreateModel(
            name='GeoStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_native', models.CharField(max_length=250, verbose_name='Название')),
                ('name_lower', models.CharField(db_index=True, editable=False, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='geodata.geocity', verbose_name='Город')),
                ('street_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='geodata.geostreettype', verbose_name='Тип улицы')),
            ],
            options={
                'verbose_name': 'улица',
                'verbose_name_plural': '5. Улицы',
                'db_table': 'geo_streets',
                'ordering': ['city', 'street_type', 'name_native'],
            },
        ),
        migrations.CreateModel(
            name='BaseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(db_index=True, max_length=30, verbose_name='Дом/Здание')),
                ('building', models.CharField(blank=True, max_length=10, verbose_name='Корпус/Строение')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс')),
                ('full_address', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Полный адрес')),
                ('normal_address', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Полный нормализованный адрес')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('city', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='geodata.geocity', verbose_name='Город')),
                ('country', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='geodata.geocountry', verbose_name='Страна')),
                ('node', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='geodata.geonode', verbose_name='Регион')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geodata.geostreet', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'базовый адрес',
                'verbose_name_plural': '6. Базовые адреса',
                'db_table': 'base_addresses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Подъезд')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)], verbose_name='Этаж')),
                ('apartment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Квартира/Офис')),
                ('intercom', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Домофон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата/время изменения')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geodata.baseaddress', verbose_name='Базовый адрес')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': '7. Адреса',
                'db_table': 'addresses',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('base', 'entrance', 'apartment'), name='unique_flat_in_base_address')],
            },
        ),
        migrations.AddIndex(
            model_name='baseaddress',
            index=models.Index(fields=['full_address'], name='base_addres_full_ad_fddd35_idx'),
        ),
        migrations.AddIndex(
            model_name='baseaddress',
            index=models.Index(fields=['latitude', 'longitude'], name='base_addres_latitud_424d08_idx'),
        ),
        migrations.AddConstraint(
            model_name='baseaddress',
            constraint=models.UniqueConstraint(fields=('street', 'house', 'building'), name='unique_physical_address'),
        ),
        migrations.AlterUniqueTogether(
            name='geostreet',
            unique_together={('city', 'name_lower'), ('city', 'street_type', 'name_native')},
        ),
    ]
