# Generated by Django 6.0b1 on 2025-10-30 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Промокод UUID')),
                ('duration', models.SmallIntegerField(default=7, verbose_name='Время жизни ( в днях )')),
                ('discount', models.SmallIntegerField(default=5, verbose_name='Скидка в %')),
                ('date_add', models.DateField(verbose_name='Дата создания')),
                ('date_end', models.DateField(blank=True, editable=False, null=True, verbose_name='Дата конца')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.PositiveSmallIntegerField(default=1, verbose_name='Quanity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shaurma', verbose_name='Шаурма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shaurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shaurma', verbose_name='Шаурма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
