# Generated by Django 6.0b1 on 2026-03-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='uniq_cart_user_item'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('session_key', 'item'), name='uniq_cart_session_item'),
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_demo_payment',
            field=models.BooleanField(default=True, verbose_name='Учебный платеж'),
        ),
        migrations.AddField(
            model_name='order',
            name='line_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка по позиции'),
        ),
        migrations.AddField(
            model_name='order',
            name='line_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма без скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='line_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма по позиции'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default='ORD-LEGACY', max_length=20, verbose_name='Код заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка по заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма заказа без скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итог по заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_name',
            field=models.CharField(default='Galactical Bank Inc.', max_length=128, verbose_name='Счёт списания'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за штуку'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shaurma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.shaurma', verbose_name='Шаурма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user', verbose_name='Пользователь'),
        ),
    ]
