# Generated by Django 6.0 on 2026-03-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_created_at_cart_meta_cart_session_key_and_more'),
        ('cart', '0002_checkout_order_archive'),
    ]

    operations = [
    ]
